language: android
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
script:
   - ./gradlew build connectedCheck